Fixing a typo
spruceid/didkit pull request #378
Opened 2023-12-15 20:50 UTC by novakboskov

This seems to be a simple typo. `http/src/config.rs` has:
```rust
#[serde_as]
#[derive(Deserialize, Debug, Clone, Hash, PartialEq, Eq)]
pub struct Issuer {
    #[serde_as(as = "Option<JsonString>")]
    pub keys: Option<Vec<JWK>>,
}
```

2023-12-15 20:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spruceid/didkit?pullRequest=378) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spruceid/didkit?pullRequest=378) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spruceid/didkit?pullRequest=378) it.</sub>

2023-12-16 08:18 UTC, sbihel requested changes
It's to document the name of the env vars. If you like you could do
```
# DIDKIT_HTTP_ISSUER_KEYS
# keys = '[<JWK>, <JWK>]'
```

2023-12-18 18:57 UTC, novakboskov commented
Agreed.

2023-12-19 16:04 UTC, sbihel approved these changes

2023-12-19 16:59 UTC, merged